### ISSUE TITLE
layout tool should update language element instead of language_label

### ISSUE THREAD

**Issue by clairebyrne** [mapaction/mapaction-toolbox#179]
## Expected Behavior
Layout tool should update **language** element on map canvas. 
Element checker should check for the presence of the **language text element** 

## Actual Behavior
Layout tool updates **language_label** element on map canvas
Element checker checks for presence of language_label text element
## Steps to Reproduce the Problem

  1. Open layout tool
  2. Change language in dropdown
  3. Observe which element has been updated on map canvas
  4. Click element checker (cog in top right of layout tool). Observe timezone element listed

## Specifications

  - Toolbar Version: 4.1.7459.3891
  - ArcGIS Version and Edition: 10.6.1
  - MapAction laptop (yes/no): no
  - Windows Version: 10

**Comment by harry-gibson** [comment]
Elements updated by the language labelling code in setLabelLanguage are identified by their names in language_config.xml i.e. the node names under each "language" root node were expected to correspond to the names of the elements on the MXD that they should provide a value for. 

This is not the case for the language name, because the "language_label" element should always have the text "Language" and the "language" element that it refers to is where the language name (referred to as 'language_label' in the XML) needs to go.

Really this is a fault in the design of the XML schema. For now, issue has been fixed by adding code to handle this node differently.

**Comment by harry-gibson** [comment]
Export tool does not respect value that has been set on map. It uses the value set in the config tool and this is what gets written to the map regardless.
