### ISSUE TITLE
Export tool makes random program window active after export completes 

### ISSUE THREAD

**Issue by stringfellow** [mapaction/mapaction-toolbox#91]
_From [ClaireBy...@gmail.com](https://code.google.com/u/110639781472218127792/) on May 17, 2014 15:37:47_

What steps will reproduce the problem? Clicked Export What is the expected output? Active window should be the 'Completed Export' alert window What do you see instead? Examples of either Windows explorer or Internet explorer becoming the active window. If you are using a MapAction computer please state which one and the path to any data you are using. laptop 63. Numerous datasets, too many to mention!. If not what version of the product are you using? On what operating system and what version of ArcMap? Please provide any additional information below. Seems like a bug but not critical.

_Original issue: http://code.google.com/p/mapaction-toolbox/issues/detail?id=91_

**Comment by andrewphilipsmith** [comment]
This is neither planned or desirable behaviour, therefore a bug.

**Comment by shurst-ma** [comment]
Hi Andy,
Was this introduced by my changes?
-Steve
On 23 May 2016 9:31 p.m., "Andy Smith" <notifications@github.com> wrote:

This is neither planned or desirable behaviour, therefore a bug.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/mapaction/mapaction-toolbox/issues/91#issuecomment-221087061>

**Comment by andrewphilipsmith** [comment]
@shurst-ma No - don't worry. This has been a long-standing (albeit minor) annoyance ;-)

**Comment by shurst-ma** [comment]
Phew.  I saw your email and panicked.

Thanks!
